config/routes.rb
Rails.application.routes.draw do
  resources :pictures do
    collection do
      post :confirm
    end
  end
  resources :sessions, only:[:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :favorites, only: [:create, :destroy, :index]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user

  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user

  mount_uploader :image, ImageUploader

  validates :title, presence: true
  validates :image, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: {maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  before_validation { email.downcase! }

  has_secure_password

  mount_uploader :self_portrait, ImageUploader

  has_many :pictures
  has_many :favorites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  before_action :logged_in_user
  def logged_in_user
    unless logged_in?
      flash[:danger] = "ログインしてください"
      redirect_to new_session_path
    end
  end


  def correct_user
    if @current_user.id != @picture.user.id
      flash[:daneger] = "他の人の投稿を編集することはできません"
      redirect_to new_session_path
    end
  end

  def correct_user?
    @user = User.find(params[:id])
    redirect_to new_session_path unless @user == current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのブログをお気に入り登録しました"
  end

  def index
    @user = current_user
    @favorites = @user.favorites
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]


  def index
    @pictures = Picture.all
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  def confirm
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end

  def edit
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    respond_to do |format|
      if @picture.save
        PictureMailer.picture_mail(@picture).deliver
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_picture
      @picture = Picture.find(params[:id])
    end

    def picture_params
      params.require(:picture).permit(:title, :image, :image_cache, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :logged_in_user

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :logged_in_user, only: [:new, :create]
  before_action :correct_user?, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # ログイン状態にするために必要
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "ブログを編集しました!"
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :self_portrait)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/views/favorites/index.html.erb
<h1><%= @user.name %>のお気に入り一覧</h1>


<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Image</th>
      <th>Content</th>
      <th>user</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @favorites.each do |favorite| %>
      <tr>
        <td><%= favorite.picture.title %></td>
        <td><%= image_tag favorite.picture.image.url %></td>
        <td><%= favorite.picture.content %></td
        <td><%= favorite.picture.user.name %></td>
        <td><%= link_to 'Show', favorite.picture %></td>
        <% if current_user.id == favorite.picture.user.id %>
          <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
          <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container clearfix">

      <div class="header clearfix">
        <a id="title">InstaClone</a>
        <% if logged_in? %>
          <%= link_to "Profile", user_path(current_user.id) %>
          <%= link_to "Logout", session_path(current_user.id), method: :delete %>
        <% else %>
          <%= link_to "Sign up", new_user_path %>
          <%= link_to "Login", new_session_path %>
        <% end %>
      </div>

      <%= yield %>
    </div>
    <div class="footer">
      <a href="#title">page up</a>
    </div>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture, local: true, url: choose_new_or_edit) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>
      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :picture_title %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
    <%= form.file_field :image, id: :picture_image %>
    <%= form.hidden_field :image_cache %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :picture_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pictures/confirm.html.erb
<h3>以下の内容で、送信する</h3>

<%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>

  <p>タイトル:<%= @picture.title %></p>
  <p>写真:<%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :image %></p>
  <p>本文:<%= @picture.content %></p>
  <p><%= form.submit "登録する" %></p>
  <% end %>

<%= form_with(model:@picture, url:new_picture_path, local:true, method:"get") do |form| %>
    <%= form.hidden_field :title %>
    <%= form.hidden_field :image_cache %>
    <%= form.hidden_field :image %>
    <%= form.hidden_field :content %>
    <%= form.submit "戻る", name: "back" %>
  <% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pictures</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Image</th>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.title %></td>
        <td><%= image_tag picture.image.url %></td>
        <td><%= picture.content %></td>
        <td><%= picture.user.name %></td>
        <td><%= link_to 'Show', picture %></td>
        <% if current_user.id == picture.user.id %>
          <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
          <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture', new_picture_path %>
<%= link_to 'Pictures', pictures_path %>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @picture.title %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @picture.image.url %>
</p>

<p>
  <strong>Content:</strong>
  <%= @picture.content %>
</p>

<% if current_user.id == @picture.user.id %>
  <%= link_to 'Edit', edit_picture_path(@picture) %> |
<% end %>

<% unless @picture.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-warning btn-sm' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-primary btn-sm' %>
  <% end %>
<% end %>
<br>
<%= link_to 'Back', pictures_path %>

app/views/users/edit.html.erb
<h1>プロフィール編集</h1>

<%= form_with(model: @user, local: true) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :self_portrait %>
    <%= f.file_field :self_portrait %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>


  <%= f.submit "Edit my profile" %>
<% end %>


<%= link_to 'Back', @user %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_with(model: @user, local: true) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.hidden_field :self_portrait %>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>'s Profile</h1>

<% if @user.self_portrait.present? %>
  <p><%= image_tag @user.self_portrait.url %></p>
<% end %>
<p>メールアドレス: <%= @user.email %></p>

<% if current_user.id == @user.id %>
  <p><%= link_to "プロフィールを編集する", edit_user_path(@user.id) %></p>
<% end %>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Image</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.pictures.each do |picture| %>
      <tr>
        <td><%= picture.title %></td>
        <td><%= image_tag picture.image.url %></td>
        <td><%= picture.content %></td>
        <td><%= link_to '詳細', picture %></td>
        <% if current_user.id == picture.user.id %>
          <td><%= link_to '編集', edit_picture_path(picture) %></td>
          <td><%= link_to '削除', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to "投稿する", new_picture_path %>
<%= link_to "投稿一覧", pictures_path %>
<%= link_to "お気に入り一覧", favorites_path %>